services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app

  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=counter_app
      - MYSQL_USER=counter
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=admin
      - TZ=Asia/Tokyo
    ports:
      - 3306

volumes:
  data: